### ISSUE TITLE
Any advice on fetching data on the paginated pages?

### ISSUE THREAD

**Issue by chmac** [infinitedescent/gatsby-pagination#10]
Firstly, thanks for this plugin, it's great.

I have 100 blog posts split into 10 paginated pages. How should I fetch the data on those paginated pages? The examples don't include the GraphQL queries.

For example, on `blog/2/`, should I pass all the data I need about each `node` into `createPaginationPages()`? Then I'm passing `title`, `date`, `excerpt`, to the `createPaginationPages` function.

Otherwise, I thought about using a `pageQuery` on the template. However, I can't figure out how to automatically get only the posts visible on that page in the query. I thought about calculating `skip` and `limit` from `pathContext`, but I don't think that is possible. ~~I could implement an `edgeParser` function and then do my calculations for `skip` and `limit` in there. Assuming those `context` values are passed to `pageQuery`.~~

I'd be grateful for any advice. Also happy to file a PR adding this to the docs if we can figure out a recommended strategy.

EDIT: Deleted the `edgeParser` suggestion, I realised I misunderstood the docs, `edgeParser` relates to creating linked pages.

**Comment by chmac** [comment]
Update. To move forward I implemented my own pagination, so I can pass `skip` and `limit` as parameters to the page and then use the same `filter` and `sort` criteria in both queries. Now I can only fetch the path in `gatsby-node.js` and all the other data in the template. Open to better ideas.

Would it make sense to add `skip` and `limit` to context in this plugin?

**Comment by haysclark** [comment]
@chmac Sorry for the long delay, and also for the docs being a little confusing.  JSDocs can be rather limited, yet I wanted to try to keep maintenance relatively easy.

> I have 100 blog posts split into 10 paginated pages. How should I fetch the data on those paginated pages? The examples don't include the GraphQL queries.

The best 'example' is to look at [gatsby-starter-casper](https://github.com/haysclark/gatsby-starter-casper).  This Gatsby started uses _gatsby-pagination_ a couple of times and also includes the GraphQL queries.

Here are some links to a functional project that is using 'gatsby-pagination', please take a look and see if it answers your questions.

[createPaginationPages example](https://github.com/haysclark/gatsby-starter-casper/blob/master/gatsby-node.js#L83-L89)
 - basic example of _createPaginationPages_
 - show the use of _limit_

[advanced createPaginationPages example](https://github.com/haysclark/gatsby-starter-casper/blob/master/gatsby-node.js#L131-L146)
 - advanced example of _createPaginationPages_
 - shows the use of _pathFormatter_
 - shows the use of _context_

[createLinkedPages and edgeParser example](https://github.com/haysclark/gatsby-starter-casper/blob/master/gatsby-node.js#L91-L103)
 - most basic example of _createPaginationPages_
 - shows the use of _edgeParser_, enabling developers to customized context payload for each 'createPage' call.
 - show use of _circular_ param

**Comment by chmac** [comment]
@haysclark Thanks for the follow up. Had a look at those examples, they're definitely useful. I'll whip up a PR to add them to the README. Done.

From reading the gatsby-starter-casper example, you're passing all of the edge data via the `pathContext`. Does it make sense to have so much data in `context`? I understood that `context` should provide enough data for the query to fetch the required data.

It seems like in the [index](https://github.com/haysclark/gatsby-starter-casper/blob/master/src/templates/index.jsx#L126) template you're fetching 2000 records from `allMarkdownRemark`. As I understand it, the component will be given 10 records via `pathContext` and will fetch 2000 of its own. So all markdown data is loaded on every single page.

Maybe I'm missing something though.

In my case, I ended up building my own pagination. I pass to the template `limit` and `skip`. Then I use those inside the template query to return only the 10 results that I need. I also have to pass in some info about `prev` and `next` paths.

**Comment by haysclark** [comment]
@chmac Thanks for the PR, questions, feedback, etc. 👍 

> From reading the gatsby-starter-casper example, you're passing all of the edge data via the pathContext. Does it make sense to have so much data in context? I understood that context should provide enough data for the query to fetch the required data.

You are correct! It is a much better practice in general in programming to pass the minimal amount of data required by another object: [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter).  In this case, it would be better to only pass the needed ID's.  I must apologize, for when I authored [gatsby-starter-casper](https://github.com/haysclark/gatsby-starter-casper/) I was pretty new to GraphQL and did not know I could [iterate over an array of variables in my query](https://stackoverflow.com/questions/40644296/how-to-query-list-of-objects-with-array-as-an-argument-in-graphql). I will look into improving _gatsby_starter_casper_ and also create a dedicated example for _gatsby-pagination_. 

> It seems like in the index template you're fetching 2000 records from allMarkdownRemark. As I understand it, the component will be given 10 records via pathContext and will fetch 2000 of its own. So all markdown data is loaded on every single page.

Good catch! That entire GraphQL query was dead code which I have [deleted](https://github.com/haysclark/gatsby-starter-casper/commit/b9d413348825854d1b84835c226dfef9c1f1e128).  Likely some form of this query will return, per the issue mentioned above.

> In my case, I ended up building my own pagination. I pass to the template limit and skip. Then I use those inside the template query to return only the 10 results that I need. I also have to pass in some info about prev and next paths.

Very cool! It would be cool to see more examples of pagination working in Gatsby.

**Comment by chmac** [comment]
@haysclark True, it's possible to query by arrays, with the significant caveat that the schema must support it! In Gatsby, according to my tests, the schema does not. For an ID field the query parameters are `eq`, `ne`, `regex` and `glob`. While it is possible to construct a regex that matches multiple values, it's not quite the same as matching on an array.

What I eventually figured out was that I didn't actually need to pass the IDs. I just pass the limit and offset parameters, and then a path to the previous and next pages in the set. Every page in the paginated set uses the same component. Therefore, it uses the same query. Therefore, the order of all results should be the same for every single page. Does that make sense?

I was worrying about order, and having some blog posts listed twice, etc. But that's a non issue. In fact, it's not even necessary to pass the `edges` to the create paginated pages function. It's sufficient to tell the function how many edges there are in total, and how many should be rendered per page.

Are you open to a PR that would add `skip` and `limit` parameters to `context`? Or would it make sense to deprecate this package in favour of `gatsby-paginate`? It also suffers from the same issue btw! Although it seems to be slightly more popular.

My immediate need has passed since I created my own functions by hand. But I could probably spend a bit of time on a PR either here or on the other package. Would be nice to try and standardise pagination in Gatsby a bit.

**Comment by haysclark** [comment]
Yes, what you wrote totally makes sense. 👍

## GraphQL types
This is possible, but very hard.  You have to dig deep into Gatsby and parse the Nodes yourself. I am hoping that there is more information about accomplishing this in the future.

## Skip and Limit
No, I do not think that it belongs in the Context data of _gatsby-pagination_, but I DO really appreciate the suggestion. I think it's such a minimal solution that one of the perks is that you don't need a 3rd party dependency.  Both _gatsby-pagination_ and _gatsby-paginate_ chunk up the data and then pass that information to and Template via the Context, which ideally should make testing a Template easier.  Your template also does not have to change if the sorting or data lookup changes.  I did this to help separate responsibilities. Passing _skip_ and _limit_ via the Context is a code-smell because it breaks the [Single Responsibility Principle](https://en.wikipedia.org/wiki/Single_responsibility_principle).

That being said, in most Gatsby Templates you are performing GraphQL queries with-in the templates, but pagination, author pages, tags, categories, and lots of other page creating logic end up inside the _gatsby_node.js_ file, which is why I pass in the data to components which are paginated.  Passing in _skip_ and _limit_ allow the GraphQL queries to remain inside the template but assumes that the data will always be linear.  There does not seem to be a perfect solution IMHO, so authors should just pick a solution they prefer.  🤷

As far as standardizing pagination, that is something to take up with Kyle Mathews. 😄

**Comment by chmac** [comment]
@haysclark Interesting. I see it differently. My interpretation of the single responsibility principle is that the pagination plugin should do one thing and one thing only. Paginate. The component is responsible for fetching its own data. That's the GraphQL way. It defines what data it needs. Right next to where its used.

I'd even argue that `context` (also called `pathContext`) is exactly that, the "context" for this path. For a path like `/blog/2` the "context" is that this path should display 15 blog posts, starting at post 16.

From my perspective, both existing pagination plugins mix concerns. Now I fetch all my data in `gatsby-node.js`. I bypass Gatsby's node system. I abuse the `context` to pass not just context data but all my data. That seems like huge code smell to me.

But hey, I also totally respect that we have differing perspectives. So after indulging myself in a little rant, I shall now stop! I'm thinking about a pagination plugin that fits my goals. I'd also love to see helpers to handle displaying of pages. Like "<< 1 2 3 **4** 5 6 7 >>" and so on.

Thanks for taking the time to reply and help me better understand your perspective. 👍
