### ISSUE TITLE
Are there any working code examples out there?

### ISSUE THREAD

**Issue by mkmanges** [infinitedescent/gatsby-pagination#11]
I have been trying to get the `gatsby-pagination` plugin to work but keep running into the same problem. My page has 8 entries and I'm setting the limit to `limit: 5`. It is creating `/example/` and `/example/2/` pages but _both_ pages display all 8 entries. 

I've looked at a few Gatsby starters (the Casper starter) that use pagination but it doesn't seem to be working on the starters, either. Does anyone have a repo that demonstrates the `gatsby-pagination` plugin working correctly? It would be a big help for me. Thx

**Comment by haysclark** [comment]
@mkmanges The best 'example' is to look at [gatsby-starter-casper](https://github.com/haysclark/gatsby-starter-casper).  The starter uses _gatsby-pagination_ a couple of times and also includes GraphQL queries.

Are you still having the issue with _limit_? I'll take a look as well.

**Comment by mkmanges** [comment]
@haysclark, thanks for responding. I have spent some time looking at the `gatsby-starter-casper` code before opening this issue. They set the the limit to 10 but have fewer than 10 items to paginate, so everything is one page. When I change the limit to 5, nothing changes--all the posts still display on one page without any pagination. I'm probably overlooking something in the documention, but I can't figure out what it is.

**Comment by haysclark** [comment]
@mkmanges Ahhh... I think I know what is happening. 💡

I believe you are experiencing Gatsby and/or browser caching issues, likely just Gatsby.  I just ran into this issue a couple minutes ago while creating the screenshot below. 

As you might know, developers need to re-run the 'develop' script every now and then, especially if the logic in _gatsby-config.js_ or _gatsby-node.js_ is changed.  Doing so will make Gatsby run the 'createPages' build step.  Unfortunately, sometimes this is not enough and you need to manually delete the ```.cache``` folder.  Even running 'clean' will not fix the issue.

Try this:
- stopping any Gatsby 'develop' threads
- run ```rm -rf .cache && rm -rf public``` to blow away the cache. 
- if you don't see any changes in your browser, try a [force refresh](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache) or a private or incognito tab.

Here is that screenshot I mentioned... hopefully, you'll be able to recreate locally. 🤞

![2018-03-07_10-54-41](https://user-images.githubusercontent.com/138324/37112609-c60ba27e-21f7-11e8-8420-a17853476a64.png)
